/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sha.pkg512;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;

/**
 *
 * @author adittachakraborty
 */

//MD2
//MD5
//SHA-1
//SHA-224
//SHA-256
//SHA-384
//SHA-512

public class SHA512 {

    public static String encryptThisString(String input) {
        try {
            //Get instance method is called with algorithm SHA-512
            MessageDigest md = MessageDigest.getInstance("SHA-512");

            //digest() method is called
            //to calculate message digest of the input string
            //returned as array of byte
            byte[] messageDigest = md.digest(input.getBytes());
            
            //Convert byte array intosignum representation
            BigInteger bi = new BigInteger(1, messageDigest);

            //Convert message digest into into hex value
            String hashText = bi.toString(16);

            //Add preceding 0s to make it 32 bit
            while (hashText.length() < 32) {
                hashText = "0" + hashText;
            }

            //Return the hashText
            return hashText;
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public static void main(String[] args) {
        System.out.println("Hash Code Generated by SHA-512 for: ");

        Scanner input = new Scanner(System.in);
        String hashCode = input.nextLine();

        System.out.println("\n" + hashCode + " : " + encryptThisString(hashCode));
    }

}
